import Input from "@/components/input";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useEffect } from "react";

const Button = dynamic(() => import('@/components/button'), { ssr: false })

export default function AboutContainer() {

  useEffect(() => {
    async function fetchingData() {
      try {
        
        // const response = await fetch('/api/hello/goodgame');
        const response = await fetch('https://jsonplaceholder.typicode.com/todos'); // external api
        const data = await response.json()
        console.log('data => ', data)
        // return data;
      } catch (error) {}
    }
    fetchingData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Input />
        <Button />
      </main>
    </>
  );
}